config/routes.rb
Rails.application.routes.draw do
  root to: "rooms#index"
  resources :rooms
  devise_for :users
  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  after_create_commit :send_to_chatters
  belongs_to :user
  belongs_to :room

  private
  def send_to_chatters
    puts 'test'
    MessageJob.perform_later(self)
  end
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  has_many :messages

  def files
    Dir["#{Rails.root.join('app', 'assets','audios').to_s}/*"].map{|file_path| file_path.split('/').last}
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :rememberable
  has_many :rooms
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    @rooms= Room.includes(:user).order(:name).all
  end

  def new
    @room= Room.new
  end

  def create
    @room= current_user.rooms.create(room_params)
    redirect_to rooms_path
  end

  def show
    @room= Room.includes(:user, :messages).find(params[:id])
  end

  def edit
    @room = Room.where(user_id: current_user.id).find(params[:id])
  end

  def update
    @room = Room.where(user_id: current_user.id).find(params[:id]).update(room_params)
    redirect_to rooms_path
  end

  private
  def room_params
    params.require(:room).permit(:name, :song_file)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Audiotorium</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1>Audiotorium</h1>
    <% unless current_user.nil? %>
      <%= link_to('Edit Profile', edit_user_registration_path)  %>
      <%= link_to('Rooms List', rooms_path) %>
      <%= link_to('Log Out', destroy_user_session_path, method: :delete) %>
    <% else %>
    <%= link_to('Log In', new_user_session_path) %>
      <% end %>
    <%= yield %>
  </body>
</html>

app/views/messages/_message.html.erb
<div>
  <div>
    <strong><%=message.user.name %></strong>:
    <br/>
    <%=message.body %>
  </div>
</div>

app/views/rooms/_form.html.erb
<%=form_for @room do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br/>
  <%= f.label :song_file %>
  <%= f.select :song_file, @room.files %>
  <br/>
  <%= f.submit %>
<% end %>

app/views/rooms/_room.html.erb
<div style="border: 1px solid black">
  <h2><%=link_to room.name, room_path(room) %></h2>
  <br/>
  <h3>is run by: <%=room.user.name%></h3>
</div>

app/views/rooms/edit.html.erb
<%= render partial: "form" %>

app/views/rooms/index.html.erb
<% unless current_user.nil? %>
  <%=link_to "Create a Room", new_room_path%>
<% end %>
<%=render @rooms %>

app/views/rooms/new.html.erb
<%= render partial: "form" %>

app/views/rooms/show.html.erb
<h2><%= @room.name %></h2>
<% if current_user == @room.user %>
  <%= link_to "Edit", edit_room_path(@room) %>
  <br/>
<% end %>
Currently Playing.. <br/> <%= @room.song_file %> <br/>
<%= audio_tag(@room.song_file, autoplay: true, controls: true) %>
<div style="width: 50%; margin-left: auto; margin-right: auto; border: 1px solid black;">
  <div  id="messages" data-room-id="<%= @room.id %>">
    <%= render @room.messages.order(created_at: :desc) %>
  </div>
</div>
<form>
  <input id='send_box' type=text'/>
</form>